name: Otonom Kaziyici Motoru

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  kazima_isleri:
    runs-on: ubuntu-latest

    steps:
      # Sürüm v4'e yükseltildi
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      # Sürüm v5'e yükseltildi
      - name: Python 3.10 Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: pip install requests beautifulsoup4

      - name: Kazıyıcıyı Başlat
        env:
          BOZKURT_API_URL: ${{ secrets.BOZKURT_API_URL }} 
        run: python resmi_gazete_kaziyici.py
